[package]
name = "RayMarcher"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
wgpu = "22"
cgmath = "0.18"
bytemuck = { version = "1.0", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
pollster = "0.3"
